version: '3.1'

services:
  app:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydb

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docs/DB/mountain.sql:/docker-entrypoint-initdb.d/mountain.sql:ro
    command: ['--default-authentication-plugin=mysql_native_password']

volumes:
  db-data:
